### ISSUE TITLE
sh = Shakkala(folder_location, version=1)，show “ValueError: GRU(reset_after=False) is not compatible with GRU(reset_after=True)“ error

### ISSUE THREAD

**Issue by SUPER-ALEX** [Barqawiz/Shakkala#48]
Hi:
When I changed sh = Shakkala(folder_location, version=3) to sh = Shakkala(folder_location, version=1), the following error occurred：

Traceback (most recent call last):
  File "/home/alex/g2p/arc/Shakkala/shakkala/demo.py", line 24, in <module>
    model, graph = sh.get_model()
  File "/home/alex/g2p/arc/Shakkala/shakkala/Shakkala.py", line 69, in get_model
    model = load_model(self.model_location)
  File "/home/alex/anaconda3/envs/arc/lib/python3.9/site-packages/keras/utils/traceback_utils.py", line 67, in error_handler
    raise e.with_traceback(filtered_tb) from None
  File "/home/alex/anaconda3/envs/arc/lib/python3.9/site-packages/keras/saving/hdf5_format.py", line 581, in _convert_rnn_weights
    raise ValueError('%s is not compatible with %s' % types)
ValueError: GRU(reset_after=False) is not compatible with GRU(reset_after=True)

**Comment by Xcoder2003X** [comment]
could i work on that
